feat : added Nav_Hero
dscnitrourkela/project-vanilla pull request #10
Opened 2024-06-06 13:36 UTC by Cybrite

2024-06-06 13:57 UTC, Srish-ty requested changes
Move images to cloudinary

2024-06-06 13:57 UTC, Srish-ty commented on src/components/marginals/Nav_Hero/content/navContent.jsx
> +export const navContent = ['Home', 'About', 'Events', 'Committee', 'Sponsors', 'Contact Us']
move content to `src/config/content/navData`

2024-06-06 13:57 UTC, Srish-ty commented on src/components/marginals/Nav_Hero/Des.jsx
> +    <article>
instead of wrapping in <article> add that in des.styles.jsx

2024-06-06 13:57 UTC, Srish-ty commented on src/components/marginals/Nav_Hero/Des.styles.jsx
> +export const DesCont = styled.div`
may use styled.article`` here

2024-06-06 13:57 UTC, Srish-ty commented on src/components/marginals/Nav_Hero/Hero.jsx
> +          <MainImg src="src/assets/Frame-h-m.png" alt="Main Frame" />
That's not how images are added in react.
refer to this https://create-react-app.dev/docs/adding-images-fonts-and-files/

2024-06-06 13:57 UTC, Srish-ty commented on src/components/marginals/Nav_Hero/Hero.jsx
> +          <Img1 src="src/assets/Group 2.png" alt="Back" />
import grp2 from "src/assets/Group 2.png"

then
```js
<img src={grp2}/>
```

2024-06-07 06:57 UTC, anmol5936 requested changes

2024-06-07 06:57 UTC, anmol5936 commented on src/components/marginals/Nav_Hero/Nav.styles.jsx
add spacing on both side of the screen as specified in the design

2024-06-07 06:57 UTC, anmol5936 commented on src/components/marginals/Nav_Hero/Nav.styles.jsx
![image](https://github.com/dscnitrourkela/project-vanilla/assets/127973342/9b6fd174-4a5c-44b4-ad20-a9c6b4d16bcd)
make it responsive

2024-06-07 06:57 UTC, anmol5936 commented on src/components/marginals/Nav_Hero/Nav.styles.jsx
![image](https://github.com/dscnitrourkela/project-vanilla/assets/127973342/29e3a82b-ce2f-4300-b50b-e49cd6e14fb0)
Size of logo in mobile size is bigger compared to the hamburger icon

2024-06-07 06:57 UTC, anmol5936 commented on src/components/marginals/Nav_Hero/Nav.jsx
> +            <LogoImg
URL and alt must be imported from config file of you component. Don't use it directly

2024-06-07 06:57 UTC, anmol5936 commented on src/components/marginals/Nav_Hero/Hero.jsx
Add all the links from config file!

2024-06-07 20:40 UTC, anmol5936 commented
@Shurtu-gal  LGTM 🚀
Please proceed with merging

2024-06-09 05:50 UTC, anmol5936 submitted a review, later dismissed

2024-06-09 09:37 UTC, anmol5936 approved these changes

2024-06-09 09:39 UTC, merged