feat: add sponsors carousel
dscnitrourkela/project-vanilla pull request #12
Opened 2024-06-06 18:16 UTC by ayanSCYY

Added sponsors carousel.

2024-06-07 06:57 UTC, anmol5936 requested changes

2024-06-07 06:57 UTC, anmol5936 commented on src/components/sponsors/sponsors.jsx
try to use map function instead of explicitly defining each Icon

2024-06-07 06:57 UTC, anmol5936 commented on src/components/sponsors/sponsors.styles.jsx
Add all the links in your component's config file and import it from there

2024-06-07 15:33 UTC, anmol5936 commented
@Shurtu-gal LGTM 🚀🚀🚀

I have reviewed the component, and it looks good to me. Please proceed with merging.

2024-06-07 16:20 UTC, Srish-ty requested changes

2024-06-07 16:20 UTC, Srish-ty commented on src/config/content/mycomp_data/sponsors.js
> +import tw from "twin.macro";
instead of `contnent/mycomp_data` created a dir `content/sponsorsData`

2024-06-07 16:20 UTC, Srish-ty commented on src/config/content/mycomp_data/sponsors.js
> +    { styles:tw`w-[202px] h-[40px] m-[90px] `, url: 'https://res.cloudinary.com/dfe8sdlkc/image/upload/v1717761140/Logo-1_vqmsdg.png' },
add responsive styling.
reduce margin and sizes for smaller screens.

2024-06-07 16:51 UTC, Srish-ty requested changes
Instead of background image, use image inside IconContainer

2024-06-07 16:51 UTC, Srish-ty commented on src/components/sponsors/sponsors.styles.jsx
> +  backgroundImage: `url(${url})`,
don't add images as backgroundimage.

use:
```js
IconContainer = styled.span``
Icon = styled.image``
```

2024-06-07 16:51 UTC, Srish-ty commented on src/components/sponsors/sponsors.jsx
> +          <Icon key={index} url={data.url} style={data.styles} />
then map over:
```js
(
<IconContainer>
    <Icon src={data.url}/>
</IconContainer>
)
```

2024-06-07 18:22 UTC, Srish-ty commented
@ayanSCYY great job ! 🚀

2024-06-09 05:28 UTC, anmol5936 approved these changes, later dismissed

2024-06-09 06:00 UTC, anmol5936 reviewed
LGTM 🚀🚀🚀

2024-06-09 06:52 UTC, anmol5936 submitted a review, later dismissed

2024-06-09 08:09 UTC, closed without merging