chore: setting up the project
dscnitrourkela/project-vanilla pull request #2
Opened 2024-06-03 16:05 UTC by Srish-ty

## Following changes are added by this pull_request:
- Set up react project with `pnpm` as package manager
- added prettier and eslint scripts for formatting and workflows

2024-06-03 16:06 UTC, Srish-ty commented
@Shurtu-gal please review

2024-06-03 16:17 UTC, Shurtu-gal reviewed
Also maybe we could use `vite` or sth else to setup the react project. For reference:- https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741

2024-06-03 16:17 UTC, Shurtu-gal commented on src/components/styles/Navbar.styles.jsx
Please make styles local to the code where it will be used. Ex: `Navbar` could have an `index.jsx` and a `style.jsx`. It would make things easier.

2024-06-03 16:17 UTC, Shurtu-gal commented on settings.json
I guess this should be in `.vscode`. And could you explain the settings purposes.

2024-06-03 16:17 UTC, Shurtu-gal commented on README.md
Please use the DSC README templates.

2024-06-03 16:23 UTC, Srish-ty commented on settings.json
The scripts (pnpm lint) for eslint were giving error : `no file found with \"src/**/*.{js,jsx}\" ` format without the settings.json

2024-06-03 16:42 UTC, Srish-ty commented on README.md
done. https://github.com/dscnitrourkela/project-vanilla/pull/2/commits/358064a4372b978f9b0a32b97ebe95dbc68f1c2b

2024-06-04 11:30 UTC, Srish-ty commented on src/components/styles/Navbar.styles.jsx
yeah. done https://github.com/dscnitrourkela/project-vanilla/pull/2/commits/e3ed2077e60ff1c93174b6510b0ae2f0f5739730

2024-06-04 16:50 UTC, Shurtu-gal requested changes
This is still left https://github.com/dscnitrourkela/project-vanilla/pull/2#pullrequestreview-2094322597

2024-06-04 16:50 UTC, Shurtu-gal commented on README.md
> +<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
Please reset it and change huckleberry to vanilla.

2024-06-04 16:50 UTC, Shurtu-gal commented on babel.config.json
> +{
Is this still required?

2024-06-04 16:50 UTC, Shurtu-gal commented on settings.json
But this should be in `.vscode` if I am not wrong.

2024-06-04 21:36 UTC, Srish-ty commented on README.md
> +<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
done

2024-06-04 21:36 UTC, Srish-ty commented
> Also maybe we could use `vite` or sth else to setup the react project. For reference:- [reactjs/react.dev#5487 (comment)](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741)

set new project up using vite.
pr link:

2024-06-05 03:02 UTC, closed without merging