Added Footer
dscnitrourkela/project-vanilla pull request #8
Opened 2024-06-05 22:33 UTC by BlessedAmrita

Added:
config->content->myFooterData.js
tailwind.config.js
components->myFooter->{MyFooter.jsx , MyFooter.styles.jsx}
added links for Poppins font in index.html

2024-06-06 10:52 UTC, Srish-ty requested changes

2024-06-06 10:52 UTC, Srish-ty commented on src/components/myFooter/MyFooter.styles.jsx
> +    px-[24px] pt-[23px] pb-[49px] custom:h-[400.3px] custom:px-[39px] custom:py-[64px] flex justify-between flex-col gap-[47px] custom:flex-row custom:gap-[0px]
custom (1450px) is too wide to add flex-col
![image](https://github.com/dscnitrourkela/project-vanilla/assets/68679980/332ade24-02ed-4174-975c-6a06fcc9681b)
make it flex-row till min 680px

2024-06-06 10:52 UTC, Srish-ty commented on tailwind.config.js
> +        customSmall: '400px'
add intermediate screen-sizes, 680px, 920px.
you've used 'custom' breakpoint everywhere, but is too wide.

2024-06-06 13:29 UTC, Srish-ty commented
@BlessedAmrita run `pnpm run lint:fix`

2024-06-07 20:43 UTC, anmol5936 commented
@Shurtu-gal  LGTM 🚀
Please proceed with merging

2024-06-08 11:47 UTC, Shurtu-gal commented
@BlessedAmrita please fix formatting.

2024-06-09 09:16 UTC, anmol5936 submitted a review, later dismissed

2024-06-09 09:21 UTC, closed without merging