feat:added about us section
dscnitrourkela/project-vanilla pull request #9
Opened 2024-06-06 06:24 UTC by ayussh-2

2024-06-06 10:14 UTC, Srish-ty requested changes
delete `pnpm-lock.yaml` file and commit changes
or `git rm pnpm-lock.yaml`

2024-06-06 10:14 UTC, Srish-ty commented on src/pages/Playground.jsx
> +      {/* <h1>Playground page</h1>
Remove the h1 and p tags. remove the commented part

2024-06-06 10:33 UTC, Srish-ty requested changes
![image](https://github.com/dscnitrourkela/project-vanilla/assets/68679980/a390b18b-33fa-4ae0-9ce8-bdd57509fccc)

make the title fonts smaller after brk-8 for mobile screens

2024-06-06 11:09 UTC, Srish-ty commented on src/components/about/aboutCard.styles.jsx
> +    ? tw`brk-8:text-[96px] brk-7:text-[96px] text-[60px] mt-20`
make the title font smaller for screens smaller than 538px. 
![image](https://github.com/dscnitrourkela/project-vanilla/assets/68679980/5516ebb8-8eb6-41f6-ac74-e9690ac834df)

2024-06-06 13:28 UTC, Srish-ty commented
@ayussh-2 run `pnpm lint:fix`

2024-06-06 15:04 UTC, ayussh-2 commented
Oook got it

2024-06-07 06:58 UTC, anmol5936 requested changes

2024-06-07 06:58 UTC, anmol5936 commented on src/components/about/About.jsx
> +          <Image
use the link by importing from config file

2024-06-07 20:42 UTC, anmol5936 commented
@Shurtu-gal  LGTM 🚀
Please proceed with merging

2024-06-09 05:26 UTC, anmol5936 approved these changes, later dismissed

2024-06-09 09:36 UTC, anmol5936 approved these changes, later dismissed

2024-06-09 09:50 UTC, anmol5936 submitted a review, later dismissed

2024-06-09 10:00 UTC, anmol5936 approved these changes

2024-06-09 10:01 UTC, merged